/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.parser.FileDistributer;
//import org.parser.XMLParser;
import org.parser.XMLReader;
import org.parser.XMLWriter;

import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // new XMLReader(FileDistributer.test_input);
        new XMLReader(FileDistributer.input);
        // new XMLWriter("C:\\Users\\johan\\projectTest\\app\\src\\main\\resources\\testMap.xml", "C:\\Users\\johan\\projectTest\\app\\src\\main\\resources\\out.xml");
    }
}
