/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.parser.FileDistributer;
//import org.parser.XMLParser;
import org.parser.XMLReader;

import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new XMLReader(FileDistributer.bolm);

    }
}
